# Generated by Django 3.0.4 on 2021-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20210611_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='presentation',
        ),
        migrations.AddField(
            model_name='settings',
            name='student_presentation',
            field=models.IntegerField(default=0, verbose_name='Продолжительность презентации студента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='teacher_presentation',
            field=models.IntegerField(default=0, verbose_name='Продолжительность презентации учителя'),
            preserve_default=False,
        ),
    ]
