# Generated by Django 3.0.4 on 2021-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20210611_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='active_percent',
            field=models.IntegerField(default=0, verbose_name='Процент выполнения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='allow_to_miss',
            field=models.IntegerField(default=0, verbose_name='Количество допустимых пропусков'),
            preserve_default=False,
        ),
    ]
