# Generated by Django 3.0.4 on 2021-06-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20210613_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='end',
            field=models.DateField(default=None, verbose_name='Конец семестра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='start',
            field=models.DateField(default=None, verbose_name='Начало семестра'),
            preserve_default=False,
        ),
    ]
